apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f src/main/docker/docker-compose.yaml -o src/main/docker/kompose-out --volumes hostPath
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: host-db
  name: host-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: host-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f src/main/docker/docker-compose.yaml -o src/main/docker/kompose-out --volumes hostPath
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: host-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PASSWORD
              value: example
            - name: POSTGRES_USER
              value: postgres
          image: postgres
          name: postgres-db
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/
              name: host-db-hostpath0
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /Users/yyi9505infocert.it/java_workspace/quarkus/quarkus-postgres-example/src/main/docker/sql
          name: host-db-hostpath0
status: {}
