apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f src/main/docker/docker-compose.yaml -o src/main/docker/kompose-out --volumes hostPath
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: host-app
  name: host-app
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "5005"
      port: 5005
      targetPort: 5005
  selector:
    io.kompose.service: host-app
status:
  loadBalancer: {}
