apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f src/main/docker/docker-compose.yaml -o src/main/docker/kompose-out --volumes hostPath
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: host-app
  name: host-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: host-app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f src/main/docker/docker-compose.yaml -o src/main/docker/kompose-out --volumes hostPath
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: host-app
    spec:
      containers:
        - image: yyi9505infocert.it/quarkus-postgres-example:1.0.0-SNAPSHOT
          name: postgres-app
          ports:
            - containerPort: 8080
            - containerPort: 5005
          resources: {}
      restartPolicy: Always
status: {}
